/* Callee-saved register state for the two supported TROE C targets. */

#include <setjmp.h>

#if defined(__aarch64__)
__asm__(".text\n"
        ".global troe_setjmp\n"
        ".type troe_setjmp, %function\n"
        "troe_setjmp:\n"
        "stp x19, x20, [x0, #0]\n"
        "stp x21, x22, [x0, #16]\n"
        "stp x23, x24, [x0, #32]\n"
        "stp x25, x26, [x0, #48]\n"
        "stp x27, x28, [x0, #64]\n"
        "stp x29, x30, [x0, #80]\n"
        "mov x2, sp\n"
        "str x2, [x0, #96]\n"
        "stp d8, d9, [x0, #104]\n"
        "stp d10, d11, [x0, #120]\n"
        "stp d12, d13, [x0, #136]\n"
        "stp d14, d15, [x0, #152]\n"
        "mov w0, wzr\n"
        "ret\n"
        ".size troe_setjmp, .-troe_setjmp\n"
        ".global troe_longjmp\n"
        ".type troe_longjmp, %function\n"
        "troe_longjmp:\n"
        "ldp x19, x20, [x0, #0]\n"
        "ldp x21, x22, [x0, #16]\n"
        "ldp x23, x24, [x0, #32]\n"
        "ldp x25, x26, [x0, #48]\n"
        "ldp x27, x28, [x0, #64]\n"
        "ldr x2, [x0, #96]\n"
        "mov sp, x2\n"
        "ldp d8, d9, [x0, #104]\n"
        "ldp d10, d11, [x0, #120]\n"
        "ldp d12, d13, [x0, #136]\n"
        "ldp d14, d15, [x0, #152]\n"
        "cmp w1, #0\n"
        "csinc w1, w1, wzr, ne\n"
        "ldp x29, x30, [x0, #80]\n"
        "mov w0, w1\n"
        "ret\n"
        ".size troe_longjmp, .-troe_longjmp\n");
#elif defined(__x86_64__)
__asm__(".text\n"
        ".global troe_setjmp\n"
        ".type troe_setjmp, @function\n"
        "troe_setjmp:\n"
        "movq %rbx, 0(%rdi)\n"
        "movq %rbp, 8(%rdi)\n"
        "movq %r12, 16(%rdi)\n"
        "movq %r13, 24(%rdi)\n"
        "movq %r14, 32(%rdi)\n"
        "movq %r15, 40(%rdi)\n"
        "leaq 8(%rsp), %rax\n"
        "movq %rax, 48(%rdi)\n"
        "movq (%rsp), %rax\n"
        "movq %rax, 56(%rdi)\n"
        "xorl %eax, %eax\n"
        "ret\n"
        ".size troe_setjmp, .-troe_setjmp\n"
        ".global troe_longjmp\n"
        ".type troe_longjmp, @function\n"
        "troe_longjmp:\n"
        "movq 0(%rdi), %rbx\n"
        "movq 8(%rdi), %rbp\n"
        "movq 16(%rdi), %r12\n"
        "movq 24(%rdi), %r13\n"
        "movq 32(%rdi), %r14\n"
        "movq 40(%rdi), %r15\n"
        "movq 48(%rdi), %rsp\n"
        "movl %esi, %eax\n"
        "testl %eax, %eax\n"
        "jnz 1f\n"
        "movl $1, %eax\n"
        "1:\n"
        "jmp *56(%rdi)\n"
        ".size troe_longjmp, .-troe_longjmp\n");
#endif
