[workspace]
resolver = "3"
members = [
    "crates/troe-application",
    "crates/troe-block",
    "crates/troe-config",
    "crates/troe-core",
    "crates/troe-dispatch",
    "crates/troe-driver",
    "crates/troe-ext4",
    "crates/troe-fat",
    "crates/troe-gpt",
    "crates/troe-machine",
    "crates/troe-memory",
    "crates/troe-vfs",
    "crates/troe-shell",
    "crates/troe-task",
    "crates/troe-terminal",
    "host",
    "kernel",
    "xtask",
]
default-members = [
    "crates/troe-application",
    "crates/troe-block",
    "crates/troe-config",
    "crates/troe-core",
    "crates/troe-dispatch",
    "crates/troe-driver",
    "crates/troe-ext4",
    "crates/troe-fat",
    "crates/troe-gpt",
    "crates/troe-memory",
    "crates/troe-vfs",
    "crates/troe-shell",
    "crates/troe-task",
    "crates/troe-terminal",
    "host",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
license = "Apache-2.0"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
panic = "abort"
strip = "symbols"
