[package]
name = "troe-ext4"
description = "Strict bounded metadata-preserving ext4 filesystem provider for TROE"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
troe-block = { path = "../troe-block" }
troe-vfs = { path = "../troe-vfs" }

[lints]
workspace = true
