[package]
name = "troe-app-printf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "troe-app-printf"
path = "src/main.rs"
test = false
bench = false

[dependencies]
troe-kex-sdk = { path = "../../sdk/rust/troe-kex" }

[lints]
workspace = true
