[package]
name = "troe-app-mem"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.troe-kex]
capabilities = ["diagnostics", "private-memory", "random"]

[[bin]]
name = "troe-app-mem"
path = "src/main.rs"
test = false
bench = false

[dependencies]
troe-kex-runtime = { path = "../../sdk/rust/troe-kex-runtime", default-features = false }
troe-kex-sdk = { path = "../../sdk/rust/troe-kex" }

[lints]
workspace = true
