[package]
name = "troe-host"
description = "Hosted Stage 0 runner for TROE"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
troe-core = { path = "../crates/common/troe-core" }
troe-shell = { path = "../crates/shell/troe-shell" }
troe-namespace = { path = "../crates/storage/troe-namespace" }
troe-fs-ramfs = { path = "../crates/storage/troe-fs-ramfs" }
troe-fs-kefs = { path = "../crates/storage/troe-fs-kefs" }

[lints]
workspace = true

