[package]
name = "troe-app-tar"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "tar"
path = "src/main.rs"
test = false
bench = false

[dependencies]
troe-kex-sdk = { path = "../../sdk/rust/troe-kex" }

[package.metadata.troe-kex]
capabilities = ["filesystem-read", "filesystem-mutate"]
stack-pages = 12

[lints]
workspace = true
