[package]
name = "troe-kernel"
description = "Firmware-hosted TROE image composition root"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
acceptance-probes = ["troe-machine/acceptance-probes"]
platform-aarch64-sbsa-ref = ["troe-machine/platform-aarch64-sbsa-ref"]
platform-aarch64-uefi-virtio-mmio = ["troe-machine/platform-aarch64-uefi-virtio-mmio"]
platform-x86_64-q35-uefi = ["troe-machine/platform-x86_64-q35-uefi"]
platform-x86_64-uefi-virtio-pci = ["troe-machine/platform-x86_64-uefi-virtio-pci"]

[dependencies]
troe-abi = { path = "../crates/common/troe-abi" }
troe-application = { path = "../crates/runtime/troe-application" }
troe-block = { path = "../crates/device/troe-block" }
troe-fmt-scfg = { path = "../crates/storage/troe-fmt-scfg" }
troe-fmt-cspk = { path = "../crates/storage/troe-fmt-cspk" }
troe-core = { path = "../crates/common/troe-core" }
troe-dispatch = { path = "../crates/runtime/troe-dispatch" }
troe-fs-api = { path = "../crates/storage/troe-fs-api" }
troe-fs-kefs = { path = "../crates/storage/troe-fs-kefs" }
troe-fs-ramfs = { path = "../crates/storage/troe-fs-ramfs" }
troe-driver = { path = "../crates/device/troe-driver" }
troe-memory = { path = "../crates/runtime/troe-memory" }
troe-fmt-bmnt = { path = "../crates/storage/troe-fmt-bmnt" }
troe-net = { path = "../crates/net/troe-net" }
troe-fmt-prgn = { path = "../crates/storage/troe-fmt-prgn" }
troe-txslot = { path = "../crates/storage/troe-txslot" }
troe-process = { path = "../crates/runtime/troe-process" }
troe-random = { path = "../crates/runtime/troe-random" }
troe-shell = { path = "../crates/shell/troe-shell" }
troe-volume = { path = "../crates/storage/troe-volume" }
troe-supervisor = { path = "../crates/runtime/troe-supervisor" }
troe-fs-statefs = { path = "../crates/storage/troe-fs-statefs" }
troe-task = { path = "../crates/runtime/troe-task" }
troe-terminal = { path = "../crates/shell/troe-terminal" }
troe-namespace = { path = "../crates/storage/troe-namespace" }
troe-fs-ext4 = { path = "../crates/storage/troe-fs-ext4" }
troe-fs-fat = { path = "../crates/storage/troe-fs-fat" }
troe-fmt-gpt = { path = "../crates/storage/troe-fmt-gpt" }
troe-identity = { path = "../crates/storage/troe-identity" }

[target.'cfg(target_os = "uefi")'.dependencies]
troe-machine = { path = "../crates/runtime/troe-machine" }
uefi = { version = "=0.39.0", features = ["alloc"] }

[lints]
workspace = true

[[bin]]
name = "kernel"
path = "src/main.rs"
test = false
bench = false
