[package]
name = "troe-app-lua"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
build = "build.rs"

[package.metadata.troe-kex]
capabilities = ["filesystem-read", "filesystem-mutate", "timer", "wall-clock", "process-launch", "pipe", "private-memory", "random"]
stack-pages = 64
heap-pages = 256

[[bin]]
name = "troe-app-lua"
path = "src/main.rs"
test = false
bench = false

[dependencies]
troe-kex-alloc = { path = "../../sdk/rust/troe-kex-alloc" }
troe-kex-runtime = { path = "../../sdk/rust/troe-kex-runtime", default-features = false, features = ["math"] }
troe-kex-sdk = { path = "../../sdk/rust/troe-kex" }

[lints]
workspace = true
