[package]
name = "troe-service-ipc-relay"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.troe-kex]
capabilities = ["persistent-endpoint", "wait-set", "diagnostics"]

[[bin]]
name = "troe-service-ipc-relay"
path = "../ipc-persistent/src/main.rs"
test = false
bench = false

[dependencies]
troe-kex-sdk = { path = "../../sdk/rust/troe-kex" }

[lints]
workspace = true
