[package]
name = "troe-fmt-prgn"
description = "Installed persistence-region selector (PRGN) format for TROE"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
troe-checksum = { path = "../../common/troe-checksum" }

[lints]
workspace = true
