[package]
name = "troe-kex-tool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
troe-abi = { path = "../../crates/common/troe-abi" }
troe-application = { path = "../../crates/runtime/troe-application" }
troe-completion = { path = "../../crates/common/troe-completion" }

[lints]
workspace = true
