[package]
name = "troe-app-rm"
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
license = "Apache-2.0"
publish = false

[package.metadata.troe-kex]
capabilities = ["filesystem-read", "filesystem-mutate"]
stack-pages = 12
heap-pages = 16

[dependencies]
troe-kex-sdk = { path = "../../sdk/rust/troe-kex" }
troe-kex-alloc = { path = "../../sdk/rust/troe-kex-alloc" }
troe-kex-runtime = { path = "../../sdk/rust/troe-kex-runtime" }

[profile.release]
codegen-units = 1
lto = false
opt-level = "z"
panic = "abort"
strip = "none"

[workspace]
