[package]
name = "troe-app-rmdir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.troe-kex]
capabilities = ["filesystem-mutate"]

[[bin]]
name = "troe-app-rmdir"
path = "src/main.rs"
test = false
bench = false

[dependencies]
troe-kex-sdk = { path = "../../sdk/rust/troe-kex" }

[lints]
workspace = true
