[package]
name = "troe-app-mv"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.troe-kex]
capabilities = ["filesystem-read", "filesystem-mutate"]
heap-pages = 4
stack-pages = 12

[[bin]]
name = "troe-app-mv"
path = "src/main.rs"
test = false
bench = false

[dependencies]
troe-kex-alloc = { path = "../../sdk/rust/troe-kex-alloc" }
troe-kex-runtime = { path = "../../sdk/rust/troe-kex-runtime" }
troe-kex-sdk = { path = "../../sdk/rust/troe-kex" }

[lints]
workspace = true
