[package]
name = "troe-vfs"
description = "Bounded namespace, embedded filesystem, and RAMFS for TROE"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
troe-core = { path = "../../common/troe-core" }
troe-fs-api = { path = "../troe-fs-api" }

[lints]
workspace = true

