[package]
name = "troe-app-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
build = "build.rs"

[package.metadata.troe-kex]
capabilities = ["filesystem-read", "filesystem-mutate", "timer", "wall-clock", "private-memory", "random"]
stack-pages = 128
heap-pages = 8192

[[bin]]
name = "troe-app-python"
path = "src/main.rs"
test = false
bench = false

[dependencies]
libm = "=0.2.16"
troe-kex-c-runtime = { path = "../../sdk/rust/troe-kex-c-runtime" }
troe-kex-runtime = { path = "../../sdk/rust/troe-kex-runtime", default-features = false }
troe-kex-sdk = { path = "../../sdk/rust/troe-kex" }

[lints]
workspace = true
